### PR TITLE
Update Readme File

### PR DESCRIPTION
**Pull request by pratik-mahalle**
Update the readme file and add its features , uses and installation using docker and other also

### CODE REVIEW

**Comment by shubham-kshetre** [comment]
You can use icons fron here: [devicon](https://github.com/devicons/devicon)

**Comment by pratik-mahalle** [comment]
I have mentioned whatever you have said, Please check it. Thanks!

**Comment by shubham-kshetre** [comment]
@pratik-mahalle You can use icon from components/social-icons

**Comment by pratik-mahalle** [comment]
OK!

**Comment by pratik-mahalle** [comment]
Update README with social icons, you can check it

**Comment by shubham-kshetre** [comment]
@pratik-mahalle I have made changes for LinkedIn only, and it seems good to me. What do you think?

**Review by pratik-mahalle — COMMENTED** [review]
It dont think it looks good, then we should apply that for all links.

**Comment by shubham-kshetre** [comment]
> It dont think it looks good, then we should apply that for all links.

Yes, It looks good to me after editing all like LinkedIn

**Comment by pratik-mahalle** [comment]
Yes, Then It will be good!

**Comment by shubham-kshetre** [comment]
> Yes, Then It will be good! We can do like this.

Go ahead and do the same with all like LinkedIn

**Comment by pratik-mahalle** [comment]
Accoriding to you, I have customized it , please review it and tell me if any update needed!

**Review by pratik-mahalle — COMMENTED** [review]
Ok

**Review by pratik-mahalle — COMMENTED** [review]
Is anything need to update now?

**Review by shubham-kshetre — APPROVED** [review]
Looks good to me!

**Comment by shubham-kshetre** [comment]
@SAYUK09 PTAL

**Comment by SAYUK09** [comment]
@shubham-kshetre You can go ahead and merge it.

**Pull request merged**
